#!/bin/sh

if [ $#  -lt 1 ]; then
    echo "./mark (part1|part2)"
    exit
fi

if [ -f tmp.file ]; then
    rm tmp.file tmp.file.2
fi

dir="$1"

echo "************* testing *************"
echo "** Compiling..."
if ! gcc -U_FORTIFY_SOURCE -Wall -Werror -O -o test test.c; then
    echo "***** [ERROR] your program did not compile. aborting! *****" 
    exit
fi

echo "** Compile Successful"

echo "** Running Tests for $dir"
for t in $dir/*.test
do
    echo "* Running \"./test < $t\""
    #./test < $t > $t.expected
    valgrind ./test < $t > tmp.file 2> tmp.file.2
    if ! diff tmp.file "$t.expected" > /dev/null; then
        echo "* Your Output: "
        cat tmp.file
        echo "* [ERROR] expected output:"
        cat $t.expected
        echo "** you have failed a test. please review it and try again"
        rm tmp.file tmp.file.2
        exit
    fi
    if ! grep "no leaks are possible" tmp.file.2 > /dev/null; then
        echo "* test passed, but there is a memory leak!"
        echo "* use 'valgrind ./test $t' to diagnose the cause"
        rm tmp.file tmp.file.2
        exit
    fi
    echo "** passed!"
done    
echo "*** all tests passed - asian father approves!"

rm tmp.file tmp.file.2
